title: Scratch Cat goes skiing
hero_image: images/banner.png
description: Create a skiing game in which you avoid obstacles
theme: orange # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: weather, games
technologies: scratch
site_areas: projects
hardware: ''
software: scratch
version: 4
last_tested: 2018-02-01
steps: 
- title: Introduction
- title: What you will need
- title: Getting started
- title: Controlling the skier
- title: Adding an obstacle
- title: Random obstacle
- title: Crashing
- title: Adding a score
- title: "Challenge: more obstacles"
