---
title: قطة تذهب للتزلج
hero_image: images/banner.png
description: قم بإنشاء لعبة تزلج تتجنب فيها العقبات
listed: true
copyedit: true
version: 4.3
last_tested: 2019-01-21
steps:
- title: المقدمة
- title: الخطوة الأولى
- title: السيطرة على المتزلج
  completion:
  - engaged
- title: إضافة عقبة
- title: 'التحدي: تغيير العقبة'
  challenge: true
- title: عقبة عشوائية
- title: الاصطدام
- title: إضافة نتيجة
  completion:
  - internal
- title: 'التحدي: عوائق أخرى'
  challenge: true
- title: ما التالي؟
