---
title: Le chat Scratch fait du ski
hero_image: images/banner.png
description: Créer un jeu de ski dans laquelle tu évites des obstacles
listed: true
copyedit: true
version: 4.3
last_tested: 2019-01-21
steps:
- title: Introduction
- title: Pour commencer
- title: Contrôler le skieur
  completion:
  - engaged
- title: Ajouter un obstacle
- title: 'Défi : changer l''obstacle'
  challenge: true
- title: Obstacle aléatoire
- title: Collision
- title: Ajouter un score
  completion:
  - internal
- title: 'Défi : plus d''obstacles'
  challenge: true